baseurl = "https://harrycresswell.com/"
theme="hc-starter"
languageCode = "en"
title = "Harry Cresswell"
pluralizelisttitles = false

# Enable for syntax highlighting
pygmentsUseClasses=true
# Enable highlighting for code fences
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

[params]
  keywords = "Product Design, UX Design, UI Design, Front-end Web Development, Small businesses, Automation, Typography"
  description = "Harry Cresswell is a professional designer and front-end web developer from London, England. Read technical articles and notes on designing and coding websites."
  strapline = "Design and front-end web development"
  location = "London, UK"
  
  # Set Cloudinary URL for image hosting
  cloudinary_url = "https://res.cloudinary.com/harrycresswell/image/upload"
  author = "Harry Cresswell"

[author]
  name = "Harry Cresswell"
  email = "studio@harrycresswell.com"
  twitter = "https://twitter.com/harrycresswell"
  github = "https://github.com/harrycresswell"
  linkedin = "https://linkedin.com/in/harrycresswell/"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
  
[permalinks]
  articles = "/:section/:slug/"
  projects = "/:section/:slug/"
  notes = "/:section/:slug/"
  page = "/:title/"

# Enable Emojis
enableEmoji = true

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 5

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 10

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 15

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 20

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 25

[[menu.footer]]
  name = "Projects"
  url = "/projects/"
  weight = 5

[[menu.footer]]
  name = "Articles"
  url = "/articles/"
  weight = 10

[[menu.footer]]
  name = "Notes"
  url = "/notes/"
  weight = 15

[[menu.footer]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 20

[[menu.footer]]
  name = "Tags"
  url = "/tags/"
  weight = 25